### ISSUE TITLE
adguardhome编译报错，go: updates to go.mod needed; to update it: go mod tidy

### ISSUE THREAD

**Issue by fxxccp** [kiddin9/openwrt-packages#117]
最近编译adguardhome屡屡报错，详细日志见附件。期待大佬分析原因所在，谢谢！

=====================

[log.txt](https://github.com/kiddin9/openwrt-packages/files/12891239/log.txt)

**Comment by fairok** [comment]
碰到一样的错误
![image](https://github.com/kiddin9/openwrt-packages/assets/3854995/8d52aee3-11fc-45d6-96bc-43280b009a21)
