### ISSUE TITLE
luci-app-godproxy 没有同步到最新

### ISSUE THREAD

**Issue by project-lede** [kiddin9/openwrt-packages#18]
如题。麻烦同步到最新。现在编译出来的有问题。

**Comment by kiddin9** [comment]
是最新的, 这个 rulesupdate.log 日志文件我这边删掉了,

**Comment by kiddin9** [comment]
不然rulesupdate.log每天更新,  我这边 https://github.com/kiddin9/packages-compile 就会每天自动编译luci-app-godproxy插件,

**Comment by project-lede** [comment]
哦。makefile文件不一样。正常编译出来是500多kb。你这边编译出来是17kb，无法运行。

**Comment by project-lede** [comment]
哦。makefile文件不一样。正常编译出来是500多kb。你这边编译出来是17kb，无法运行。

**Comment by kiddin9** [comment]
luci就只有这么大吧, 这个依赖 https://op.supes.top/packages/x86_64/koolproxy_3.8.5-1_x86_64.ipk 并不包含在luci中的.

**Comment by project-lede** [comment]
我再测试下。看看是不是我那边有问题

**Comment by project-lede** [comment]
makefile文件里面
PKG_NAME:=luci-app-godproxy
PKG_VERSION:=3.8.5
PKG_RELEASE:=3-20211121
你这边编译出来的是koolproxy3.8.5-1。应该是3.8.5-3.我看了只你克隆luci。没有克隆luci下的koolproxy文件夹。

**Comment by kiddin9** [comment]
如果没有luci, koolproxy就没法运行的话, 其实没必要把koolproxy单独弄成插件,官方的之所有都分开是因为即使没有对应的Luci,主程序也是包含init文件可以运行的.

**Comment by kiddin9** [comment]
Luci只是多了个操作的途径罢了.

**Comment by project-lede** [comment]
好的。在测试下。
