### ISSUE TITLE
luci-app-qbittorrent

### ISSUE THREAD

**Issue by erdoukki** [kiddin9/openwrt-packages#22]
init.d modify the Downloads\SavePath and do not set correctly the $download_dir
resolved by https://github.com/kiddin9/openwrt-packages/pull/21

**Comment by kiddin9** [comment]
The $download_dir set at https://github.com/kiddin9/openwrt-packages/blob/e0414a15d01a3db5b3b8a9174e723ba80d2aff2c/luci-app-qbittorrent/root/etc/init.d/qbittorrent#L21

**Comment by erdoukki** [comment]
Yes, but this result in my case of a bad setting !
I am stuck with a partly deleted Downloads\Save instead of being modify by the sed ...

here are my configs;

root@ULTRA-5G:~# cat /etc/config/qbittorrent 
```
config qbittorrent
	option port '8888'
	option profile_dir '/etc/qbittorrent/'
	option download_dir '/mnt/ls421de/RECUP/torrent/'
	option enable '1'
```

**Comment by kiddin9** [comment]
Got it, I stand corrected, Thanks.
