### ISSUE TITLE
编译 v2ray-core 报错

### ISSUE THREAD

**Issue by Qs315490** [kiddin9/openwrt-packages#25]
$ make -j1 V=s package/feeds/custom/v2ray-core/compile

................
no required module provides package github.com/v2fly/v2ray-core/v4/main; to add it:
	go get github.com/v2fly/v2ray-core/v4/main

Building targets
no Go files in /home/qs315490/openwrt/build_dir/target-aarch64_generic_musl/v2ray-core-5.0.3/.go_work/build

make[2]: *** [Makefile:189: /home/qs315490/openwrt/build_dir/target-aarch64_generic_musl/v2ray-core-5.0.3/.built] Error 1
make[2]: Leaving directory '/home/qs315490/openwrt/feeds/custom/v2ray-core'
time: package/feeds/custom/v2ray-core/compile#1.46#0.79#2.07
    ERROR: package/feeds/custom/v2ray-core failed to build.
make[1]: *** [package/Makefile:114: package/feeds/custom/v2ray-core/compile] Error 1
make[1]: Leaving directory '/home/qs315490/openwrt'
make: *** [/home/qs315490/openwrt/include/toplevel.mk:230：package/feeds/custom/v2ray-core/compile] 错误 2

$ cd build_dir/target-aarch64_generic_musl/v2ray-core-5.0.3
$ go get github.com/v2fly/v2ray-core/v4/main
build github.com/v2fly/v2ray-core/v4/main: cannot load io/fs: malformed module path "io/fs": missing dot in first path element

**Comment by kiddin9** [comment]
已修复.
