### ISSUE TITLE
希望加入灵缇加速器的luci

### ISSUE THREAD

**Issue by Chikage0o0** [kiddin9/openwrt-packages#26]
项目地址：https://github.com/Droid-MAX/luci-app-lingtigamebooster

**Comment by kiddin9** [comment]
这个插件不完善,还得自己手动去下载对应的bin文件,

**Comment by Chikage0o0** [comment]
https://github.com/esirplayground/luci-app-LingTiGameAcc
https://github.com/esirplayground/LingTiGameAcc
刚刚查看了一下 esir的使用没问题
