### ISSUE TITLE
能否加一下comfast cf811ac 网卡驱动

### ISSUE THREAD

**Issue by gngpp** [kiddin9/openwrt-packages#30]

**Comment by kiddin9** [comment]
驱动是 rtl8821cu 已经包含了.

**Comment by zf1976** [comment]
> 驱动是 rtl8821cu 已经包含了.

这种驱动是不能编译成ipk安装吗，直接集成固件里？，有没有源码跟编译步骤参考下

**Comment by zf1976** [comment]
![D957DE3F-CD43-4BCF-AA4A-3B2BB1FF19EE](https://user-images.githubusercontent.com/51810656/154836236-af8fc7bc-eaab-462d-abbf-1df14f0498bb.png)

**Comment by kiddin9** [comment]
你用的不是我的固件,我的固件可以在后台软件包中直接下载安装此驱动

**Comment by zf1976** [comment]
> 你用的不是我的固件,我的固件可以在后台软件包中直接下载安装此驱动
> 

好
