### ISSUE TITLE
cups 与 libcups 版本不符

### ISSUE THREAD

**Issue by a76yyyy** [kiddin9/openwrt-packages#68]
cups 版本是2.3.3
libcups 版本是 2.2.12
使用 `/etc/init.d/cupsd start` 提示
```
Error relocating /usr/sbin/cupsd: _cupsMessageSave: symbol not found
```
怀疑是版本不匹配的原因

**Comment by sky0504** [comment]
我也有同样的错误，不知道是怎么回事
https://op.supes.top/packages/mipsel_24kc/old/luci-app-cupsd_git-22.147.57852-d7e4f23_all.ipk
https://op.supes.top/packages/mipsel_24kc/old/luci-app-cupsd_git-23.260.37888-e2c1089_all.ipk
https://op.supes.top/packages/mipsel_24kc/luci-app-cupsd_git-23.303.44828-ba42a9a_all.ipk

使用这三个包分别卸载重新安装，都是显示此错误

```
Error relocating /usr/sbin/cupsd: _cupsMessageSave: symbol not found
```

**Comment by sky0504** [comment]
https://op.supes.top/packages/mipsel_24kc/old/libcups_2.3.3-16_mipsel_24kc.ipk 确实是libcups版本不对的原因。下载这个ipk，然后安装上去cups就不会报错了，可以正常启动了
