### ISSUE TITLE
chinadns-ng和dns2tcp缺少config以及init

### ISSUE THREAD

**Issue by oTnTh** [kiddin9/openwrt-packages#86]
这位大佬提供了相关的配置文件和启动脚本，不知道是否方便搬过来用：

[https://github.com/pexcn?tab=repositories]

**Comment by kiddin9** [comment]
已更换.

**Comment by oTnTh** [comment]
a53版本的ipk我装上试了试，目前看起来没什么问题。

非常感谢。
