### ISSUE TITLE
软件源报错

### ISSUE THREAD

**Issue by Rehtt** [kiddin9/openwrt-packages#92]
opkg_download: Failed to download https://op.supes.top/packages/x86_64/Packages.gz, wget returned 8.

看样子是没过cf盾

**Comment by Rehtt** [comment]
~ # wget https://op.supes.top/packages/x86_64/Packages.gz
--2023-03-30 11:48:00--  https://op.supes.top/packages/x86_64/Packages.gz
Resolving op.supes.top... 104.21.67.53, 172.67.213.212
Connecting to op.supes.top|104.21.67.53|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2023-03-30 11:48:01 ERROR 403: Forbidden.

**Comment by kiddin9** [comment]
修复了.

**Comment by XiaoLrrr** [comment]
> 修复了.

能修复一下N1 A53的源吗，同样的问题
