### ISSUE TITLE
x86 更新列表报错

### ISSUE THREAD

**Issue by kiruya1987** [kiddin9/openwrt-packages#93]
Downloading https://op.supes.top/packages/x86_64/Packages.gz
*** Failed to download the package list from https://op.supes.top/packages/x86_64/Packages.gz

Downloading https://op.supes.top/packages/x86_64/base/Packages.gz
*** Failed to download the package list from https://op.supes.top/packages/x86_64/base/Packages.gz

Downloading https://op.supes.top/packages/x86_64/packages/Packages.gz
*** Failed to download the package list from https://op.supes.top/packages/x86_64/packages/Packages.gz

Downloading https://op.supes.top/packages/x86_64/luci/Packages.gz
*** Failed to download the package list from https://op.supes.top/packages/x86_64/luci/Packages.gz

Downloading https://op.supes.top/packages/x86_64/routing/Packages.gz
*** Failed to download the package list from https://op.supes.top/packages/x86_64/routing/Packages.gz

Downloading https://op.supes.top/packages/x86_64/Packages.gz
*** Failed to download the package list from https://op.supes.top/packages/x86_64/Packages.gz

Collected errors:
 * opkg_download: 下载失败 https://op.supes.top/packages/x86_64/Packages.gz, wget returned 8.
 * opkg_download: 下载失败 https://op.supes.top/packages/x86_64/base/Packages.gz, wget returned 8.
 * opkg_download: 下载失败 https://op.supes.top/packages/x86_64/packages/Packages.gz, wget returned 8.
 * opkg_download: 下载失败 https://op.supes.top/packages/x86_64/luci/Packages.gz, wget returned 8.
 * opkg_download: 下载失败 https://op.supes.top/packages/x86_64/routing/Packages.gz, wget returned 8.
 * opkg_download: 下载失败 https://op.supes.top/packages/x86_64/Packages.gz, wget returned 8.

**Comment by kiruya1987** [comment]
好像是SSR出了问题导致的

**Comment by Ohraf1** [comment]
您解决了吗
